### ISSUE TITLE
never mind.. 👀

### ISSUE THREAD

**Issue by Meow764** [Fraserbc/BetterDiscord-Embeds#1]
Pretty sure it's not working unless I'm retarded.
I think the listener may not be targeting the correct css element, or whatever you'd call it.

EDIT: Yup, I was just being retarded.

**Comment by Fraserbc** [comment]
Have you put your client token in? You can get it by going to discordapp.com, developer tools, local storage and copy your token from there.

**Comment by Meow764** [comment]
Sure, wasn't able to get it quite that way, but I recorded network activity when loading a discord page and then filtered by `/api`.
But even if the token was wrong, `/e test` should do something else than just normally sending the message.

**Comment by Meow764** [comment]
Nevermind, it's all good. I indeed was being retarded. Don't even want to say what I had fucked up lmfao.

**Comment by Fraserbc** [comment]
Thanks for the link though, I'll work on that. Also, would you mind sharing what you did wrong so I can add that in a section I'm writing on installation and troubleshooting?

**Comment by Meow764** [comment]
Had an older send embeds plugin, and accidentally in plugin settings enabled that one instead of this newer one.
Guess you could write "ensure you have the plugin turned on" lmfao.

**Comment by Fraserbc** [comment]
Ahh ok thanks :)
