### ISSUE TITLE
Send URL in Description

### ISSUE THREAD

**Issue by kanekireal** [Fraserbc/BetterDiscord-Embeds#15]
Hello, I can't send URL (https:// or http:// or just have ":" in description ).

`/e title: 
description: :flag_fr: **__FastMMO__**, est un jeu multijoueur massif en ligne, basé sur du __**Farm** *intense et rapide*__.

Parcourez l'univers avec des __**Butins** *de plus en plus extraordinaires*__ à chaque **Étape** que vous faites...

Devenez la __**Légende** *parmi tant de nobles personnes*__...

Entrainez-vous à attaquer des simples ennemies avant de __**terrasser** *les autres joueurs*__...

Effectuez des **quêtes**, remplissez des **emplois**, et __*bien plus*__...

Rejoignez la __**communauté** *afin de discuter de vos différents équipements*__ et de savoir qui est **le plus fort** d'entre-vous...

**Jouez dès maintenant à FastMMO !**

Site officiel » https://fastmmo.wesley-dev.codes
Discord » https://discord.gg/GuCBfpp
url: https://fastmmo.wesley-dev.codes
color: #424DC8
thumbnail: https://cdn.probot.io/yiyacQ4nK8.png
author: FastMMO
author_url: https://cdn.probot.io/yiyacQ4nK8.png
author_icon: https://cdn.probot.io/yiyacQ4nK8.png`

How to resolve this problem ?

An idea: 

Make: description: ""
No looking for chest after : because you will have this error.
Or also, looking prefix -> contains("descrpition:") looking while after another prefix. Thanks to resolve this fast

**Comment by Fraserbc** [comment]
Hi there!
I'm extremely sorry about not responding for this for 7 months so I doubt you still care but it works now with the latest refactor

**Comment by kanekireal** [comment]
Hii,

Okay thanks ;D
