### ISSUE TITLE
Embeds not working.

### ISSUE THREAD

**Issue by Megalith9** [Fraserbc/BetterDiscord-Embeds#18]
Plugin cannot start after uninstalling and installing BetterDiscord Beta Installer.

**Comment by Seewak342** [comment]
Same

**Comment by Fraserbc** [comment]
Ok, BetterDiscord recently deprecated JQuery which broke my plugin. I've just pushed a commit that should fix this. Can you try redownloading it and trying again

**Comment by Megalith9** [comment]
Thank you! It worked for me
