### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KNPKOPOB** [Fraserbc/BetterDiscord-Embeds#2]
When i try to create a embed message the error comes out:
Uncaught ReferenceError: DiscordInternals is not defined
    at sendEmbed
at HTMLTextAreaElement.handleKeypress 
at HTMLTextAreaElement.i

**Comment by Fraserbc** [comment]
Sorry for not responding, I had a lot of school work to get though. Where does that error come out? In the dev tools? Can you please send a screenshot so I can help further.

**Comment by Fraserbc** [comment]
Also just try opening discord again

**Comment by KNPKOPOB** [comment]
Wow. I installed Lib Discord Internals v1.13 by Samogot and it work. Thnx .
