### ISSUE TITLE
Won't embed

### ISSUE THREAD

**Issue by Phinlorian** [Fraserbc/BetterDiscord-Embeds#20]
idk if im just stupid but i copied

/e title: My cool title
description: Cool embeds
Wow! Multiline
url: https://discordapp.com
color: #1243ff
timestamp: true
footer_image: https://cdn.discordapp.com/embed/avatars/0.png
footer: WOW! Footers!
thumbnail: https://cdn.discordapp.com/embed/avatars/0.png
image: https://cdn.discordapp.com/embed/avatars/0.png
author: ABCD
author_url: https://discordapp.com
author_icon: https://cdn.discordapp.com/embed/avatars/0.png

and posed it in a chat and nothing happened. I didn't have a problem with it not sending like with other people, it just doesnt embed.
![Screenshot_69](https://user-images.githubusercontent.com/55641240/113458729-40dbbf80-93e1-11eb-8158-92db42b1eca5.png)

**Comment by Phinlorian** [comment]
(to add I did download the plugin that you said to download if it didn't work and the same problem occurs)

**Comment by Fraserbc** [comment]
Hi, can you test going to your friends list then pressing CTRL+R to reload discord. This may or may not fix the issue and if so is just a temporary workaround while I try and debug it

**Comment by Phinlorian** [comment]
Same issue presists
![Screenshot_70](https://user-images.githubusercontent.com/55641240/113461007-b8611d00-93e8-11eb-8884-be66eaa09a47.png)
