### ISSUE TITLE
Not Working (Plugin is not starting)

### ISSUE THREAD

**Issue by Legend82825** [Fraserbc/BetterDiscord-Embeds#22]
When i start the quoter plugin it throws an error saying "Quoter could not be started"

**Comment by IronGunYT** [comment]
Also this problem. I have the newest better discord. Lib Discord Internalsv1.13 is on, but i can't start both quoter or send embeds.

**Comment by IronGunYT** [comment]
![image](https://user-images.githubusercontent.com/23254987/113509474-74902400-955e-11eb-913b-d80392aef228.png)

**Comment by bigbenster702** [comment]
Yep, same thing is going on with me.

**Comment by kingpin1905** [comment]
The New BetterDiscord update broke the plugin.

**Comment by TheNochtgamer** [comment]
yeah, the plugin starts but it simple don't work anymore, i tried with "/e title: test".

**Comment by bigbenster702** [comment]
The creator said in another post to reinstall the plugin and that worked for me.
