### ISSUE TITLE
not working. 

### ISSUE THREAD

**Issue by Godwhitelight** [Fraserbc/BetterDiscord-Embeds#25]
Send Embeds Faild to lunch

**Comment by Toskan4134** [comment]
x2, when i try to send this message, the plugin doesn't let me send it

/e title: My cool title
description: Cool embeds
Wow! Multiline
url: https://discordapp.com
color: #1243ff
timestamp: true
footer_image: https://cdn.discordapp.com/embed/avatars/0.png
footer: WOW! Footers!
thumbnail: https://cdn.discordapp.com/embed/avatars/0.png
image: https://cdn.discordapp.com/embed/avatars/0.png
author: ABCD
author_url: https://discordapp.com
author_icon: https://cdn.discordapp.com/embed/avatars/0.png

**Comment by ArjixGamer** [comment]
works for me, are you on the latest version?

**Comment by Toskan4134** [comment]
Yes

**Comment by Godwhitelight** [comment]
i fixed it by updating

**Comment by UnstoppableYash** [comment]
Same for me, the message doesn't send and the embed doesn't create as well :(

**Comment by DS-GitHub** [comment]
works well
