### ISSUE TITLE
Does not work on OSX

### ISSUE THREAD

**Issue by RelievedStudios** [Fraserbc/BetterDiscord-Embeds#3]
This plugin works on my windows machine but not on my mac book, it detects the /e because when I go to send a message with it nothing is send but it doesn't send the embedded message

**Comment by Fraserbc** [comment]
Hmm I don't have an apple device to test on but I can work on it if you help me. Can you post a dump of the dev tools. You can open this with Ctrl + Shift + I

**Comment by RelievedStudios** [comment]
sorry for late reply, here is the error it seems to throw

### what gets copied to clipboard when I copy the error:

  | sendEmbed | @ | /Users/owen/Library/…Embeds.plugin.js:59
-- | -- | -- | --
  | handleKeypress | @ | /Users/owen/Library/…mbeds.plugin.js:125
  | i | @ | 84866f1….js:49

### image of actual error:
[image](https://owenscode.org/files/images/Screen%20Shot%202019-05-21%20at%204.38.10%20pm.png)

**Comment by RelievedStudios** [comment]
this appears to be the same error as in the [Error](https://github.com/Fraserbc/BetterDiscord-Embeds/issues/2) post so it might be related

**Comment by Fraserbc** [comment]
Hmmm. Can you type "Discord" into the console and screenshot the autocomplete for it?

**Comment by Fraserbc** [comment]
You need to install this plugin for it to work correctly
https://github.com/samogot/betterdiscord-plugins/blob/master/v1/1lib_discord_internals.plugin.js

**Comment by RelievedStudios** [comment]
Hey sorry for late reply, haven't had access to the mac in a little while. that fixed it up right away! thanks!
