### ISSUE TITLE
Embeds aren't sending when pressing Enter.

### ISSUE THREAD

**Issue by StupidRepo** [Fraserbc/BetterDiscord-Embeds#32]
It was working once then it stopped working.

**Comment by xartuu** [comment]
The fix is on its way! We are waiting for the author to approve the PR (https://github.com/Fraserbc/BetterDiscord-Embeds/pull/36).

**Comment by iDCoded** [comment]
> 
> 
> It was working once then it stopped working.

I had the same problem but then I refreshed Discord (Ctrl + R)
Then I was able to send by pressing Enter, but the embed wasn't working as intended. 
No luck either ways.
