### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by iOuroborosS** [Fraserbc/BetterDiscord-Embeds#35]
This could be the best plugin ever, so to speak, but why doesn't it work anymore?
I could cry.

Please fix it !!!!!!

**Comment by TheNochtgamer** [comment]
I think the creator abandoned this plugin, i hope someone save the day by making another one of this kind

**Comment by xartuu** [comment]
The fix is on its way! We are waiting for the author to approve the PR (https://github.com/Fraserbc/BetterDiscord-Embeds/pull/36).

**Comment by lesleyxyz** [comment]
Solved & merged in #36

**Comment by willyman202** [comment]
this plugin just stopped working right now. I don't know what the reason might be. Kindly look into this as soon as possible. This is best so far

**Comment by dav1312** [comment]
Discord finally patched it, no more embeds for users HAHAHA

**Comment by D3F3ND3R1538** [comment]
damn this embeds thing was so nice while it lasted oh well!
