### ISSUE TITLE
When creating a embed, nothing is sent.

### ISSUE THREAD

**Issue by Mr-Foxtrot** [Fraserbc/BetterDiscord-Embeds#4]
I disabled and re-enabled all of my plugins, restarted discord, re-downloaded the internal lib plugin.
Im sure the plugin might have broke from some of discords more heavy changes from updates.

Is this planned to be fixed soon or is this repository dead?

**Comment by Fraserbc** [comment]
It still works for me. Can you provide some more details like a log of the dev console?

**Comment by Mr-Foxtrot** [comment]
> 
> 
> It still works for me. Can you provide some more details like a log of the dev console?

Nevermind, I looked through the console and found out it was another plugin causing some trouble with the embed plugin.

though do you mind if I ask, is it possible to send images within the embed?

**Comment by Fraserbc** [comment]
Currently it is not possible however due to request I am working on adding that functionality
