### ISSUE TITLE
Plugin recently broken

### ISSUE THREAD

**Issue by Luciferrari** [Fraserbc/BetterDiscord-Embeds#5]
Title says it all; details are that it just doesn't work the same as it used to.
Used to be able to put 
 **_/e "what up"_**
and it'd make a pretty basic embed. Now it literally just puts what I type. Any change in syntax or is it just broken?

**Comment by Fraserbc** [comment]
The syntax was changed to allow images. Please check the README

**Comment by Fraserbc** [comment]
This has been inactive for 22 days. Closing
