### ISSUE TITLE
Will not send embed as of today

### ISSUE THREAD

**Issue by Ruvalian** [Fraserbc/BetterDiscord-Embeds#6]
Hello,

This plugin is not functional. I downloaded and installed it today.

When attempting to send an embed, this error appears in the console:
1158ba5343d0881e400d.js:16 Uncaught TypeError: MessageParser.createMessage is not a function
    at sendEmbed (C:\Users\Sonador\AppData\Roaming\BetterDiscord\plugins\SendEmbeds.plugin.js:51)
    at HTMLDivElement.handleKeypress (C:\Users\Sonador\AppData\Roaming\BetterDiscord\plugins\SendEmbeds.plugin.js:244)
    at HTMLDivElement.r (1158ba5343d0881e400d.js:16)

The message does not send, the chat box does not clear.

The format of the command I am sending is:
/e title: fuck
description: cunts
url: tiny.cc/PAIN
color: #ff0000
timestamp: true
footer_image: https://i.imgur.com/vsEAFd5.png
footer: absolute bastard
thumbnail_image: https://i.imgur.com/vsEAFd5.png
image_url: https://i.imgur.com/vsEAFd5.png
author: unscrupulous nonsense
author_url: tiny.cc/PAIN
author_icon: https://i.imgur.com/vsEAFd5.png

I am on BBD v0.2.21. Lib Discord Internals v1.13 is installed. I have verified both plugins are enabled and rebooted my client.

Please let me know if any further information is needed.

**Comment by Fraserbc** [comment]
Hi, please try it again. It is working for me again.

**Comment by Fraserbc** [comment]
This has been open for 22 days now with very little activity. Closing. Open a new issue if the problem persists
