### ISSUE TITLE
Multiple lines dont work

### ISSUE THREAD

**Issue by Headteachers** [Fraserbc/BetterDiscord-Embeds#8]
Adding multiple lines to the **description** value doesn't work, I've tried to contact you (the owner of the project) on Discord regarding a fix or an update on that but haven't received a response?

So I'll ask here, is there any progress on fixing this?? Cause atm it renders it kind of useless not being able to add any lines

**Comment by Headteachers** [comment]
@Fraserbc

**Comment by Fraserbc** [comment]
Multiline support has been added. Closing
